Iter13
anoriar/shortener pull request #13
Opened 2023-10-15 19:47 UTC by anoriar

2023-10-16 10:48 UTC, gonozov0 requested changes
Отличная работа, на вопросы в коде ответил
Давай уберем из main и из инициализации роутера всю логику для инициализации базы данных, она должна вызываться внутри NewDBURLRepository/InitializeDBURLRepository, а сам пакет db внутри repository/db/internal

2023-10-16 10:48 UTC, gonozov0 commented on cmd/e2e/shortener_test.go
> +// через httptest.NewServer -? тогда надо переиницилазировать весь хендлер и по сути выполнять всю внутрянку main.go сервера + зависимости
каждый e2e должен уметь подчищать за собой созданные объекты, для этого тебе нужно разработать delete ручки

2023-10-16 10:48 UTC, gonozov0 commented on internal/e2e/client/dto/response/ping_response_dto.go
> +}
Интересно, почему решил не использовать http статус код?

2023-10-16 10:48 UTC, gonozov0 commented on internal/shortener/db/database.go
> +// Если здесь сделать интерфейс - можно будет протестить pingHandler через мок
Если честно, не совсем понимаю, почему ты в pingHandler не используешь URLRepositoryInterface, надо просто расширить этот интерфейс методом Ping, а все, что касается базы данных, которое необходимо для DatabaseURLRepository нужно положить в db/internal и инициализировать в NewDBURLRepository/InitializeDBURLRepository, а не гдето еще в других местах, особенно в main

2023-10-16 10:48 UTC, gonozov0 commented on internal/shortener/db/database.go
> +// Но для postgres не работает IF NOT EXISTS и выведет ошибку
[Postgres точно умеет в if not exists](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-PARMS-IF-NOT-EXISTS), скорее всего у тебя какая-то проблема в коде, какую ошибку выдает?

2023-10-16 10:48 UTC, gonozov0 commented on internal/shortener/db/migrations/version231009.go
> +package migrations
Если ты хочешь в своем в проекте подключить полноценный механизм миграций, то рекомендую `golang-migrate/migrate`, сами миграции намного лучше и удобнее писать в sql файлах

2023-10-16 10:48 UTC, gonozov0 commented on internal/shortener/repository/db/db_url_repository.go
> +// С точки зрения DDD - плохая практика, а также замусоривает  параметры функции
Если того требует sql.DB, то да, это нормальная практика. Не совсем понимаю, почему это плохая практика с точки зрения DDD, расширь плиз поинт.

При этом ты же можешь спокойно использовать такие же методы sql.DB, которые не требуют контекста. Я обычно их и использую, нужно всегда понимать, для чего тебе необходимо вызвать метод с контекстом, это обычно необходимо при тяжелых запросах в бд для их отмены либо по таймауту, либо когда клиент разоравал соединение с сервером.

2023-10-16 10:48 UTC, gonozov0 commented on internal/shortener/repository/db/db_url_repository.go
> +// Нужно ли проверять коннект к бд и реконнектить в случае неуспешного пинга? Как отличить: потерялся коннект к бд или ошибка запроса?
Может конечно, но под капотом драйвер базы данных установит новое соединение или возьмет уже существующее из пула

Второго вопроса не понял, мне кажется у тебя есть недопонимание, что такое коннект к бд, если провалиться в метод Connect, то станет понятно, что это просто открытие пула соединений + пинг. 

Поэтому вызывать реконнект в момент запроса - это бессмысленная затея. Если проблема была на стороне go приложения, например, неверные параметры подключения, или нет сетевого доступа, то она бы стала понятная в момент старта. В момент запроса по бизнес логике у тебя уже берется существующее соединение или создается новое + ты выполняешь сам запрос (пинг - это по сути тоже обычный запрос, прост с пустым селектом)

2023-10-16 17:52 UTC, anoriar commented on internal/e2e/client/dto/response/ping_response_dto.go
> +}
Не понял вопроса?
Это dto ответ клиента, здесь может прийти любой int

2023-10-16 17:55 UTC, anoriar commented on internal/shortener/db/database.go
> +// Если здесь сделать интерфейс - можно будет протестить pingHandler через мок
Насчет интерфейса: ping для файлового и инмемори хранилища? В плане контекста пинг этим репозиториям плохо подходит
Более того: ping должен работать отдельно, проверяя, работает ли база данных. 
Мы можем, например, поставить DATABASE_DSN="", при этом автотест все равно запустит команду ping и он должен получить ошибку в этом случае, т к бд не работает

2023-10-16 19:19 UTC, anoriar commented on internal/shortener/db/database.go
> +// Если здесь сделать интерфейс - можно будет протестить pingHandler через мок
Переделал
Код стал действительно чище
Правда все равно в main.go инициализирую репозиторий
Для того чтобы закрыть коннект с базой

2023-10-16 19:22 UTC, anoriar commented on internal/shortener/db/database.go
> +// Но для postgres не работает IF NOT EXISTS и выведет ошибку
уже не актуально

2023-10-16 19:29 UTC, anoriar commented on internal/shortener/repository/db/db_url_repository.go
> +// С точки зрения DDD - плохая практика, а также замусоривает  параметры функции
Почему с точки зрения DDD плохая практика:
Контекст - это инфраструктура проекта
Если мы нашу доменную модель entity.URL с интерфейсом UrlRepositoryInterface перенесем в проект на другом языке - там это работать не будет.
Зависимость доменной модели от инфраструктуры получается

2023-10-16 20:39 UTC, anoriar commented on internal/shortener/db/migrations/version231009.go
> +package migrations
Переписал, очень интересный опыт
Особенно с учетом того, что по ТЗ надо поднимать миграции при поднятии сервера

Вопрос:
Что делать, если надо добавить уникальный индекс на поле, но миграция будет возвращать ошибку, т к в поле уже есть дублирующиеся записи. Это можно решить с помощью одного sql?
Ведь с дубликатами нужно что-то делать. Например, добавлять в конец инкремент: short-url-1, short-url-2

2023-10-17 21:33 UTC, anoriar commented on cmd/e2e/shortener_test.go
> +// через httptest.NewServer -? тогда надо переиницилазировать весь хендлер и по сути выполнять всю внутрянку main.go сервера + зависимости
Сделал DELETE метод - по shortURL удаляет записи в бд
e2e тесты дополнил

2023-10-18 08:14 UTC, gonozov0 approved these changes
Все моменты поправлены, апрув 👍

2023-10-18 08:14 UTC, gonozov0 commented on internal/e2e/client/dto/response/ping_response_dto.go
> +}
Ага, ок, не разобрался до конца сначала, думал, что это не для тестов, а для хендлера возвращается такая структура

2023-10-18 08:14 UTC, gonozov0 commented on internal/shortener/db/migrations/version231009.go
> +package migrations
Отличный вопрос, зависит от ситуации, обычно если принимается решение навесить уникальный индекс, то это означает, что дубликатов в принципе не должно быть в базе. Если вдруг они есть, то тут дальше 2 пути:
1. Решение о том, что это поле уникальное - ошибочное и если нам нужен индекс, то создаем его без уникальности
2. Дубликаты возникли по какой-то ошибке в бизнес логике и их надо удалить. Обычно для этого пишется oneshot еще до миграции, прогоняется на проде, после чего дубликатов по этому полю не остается в базе

2023-10-18 08:14 UTC, gonozov0 commented on internal/shortener/repository/db/db_url_repository.go
> +// С точки зрения DDD - плохая практика, а также замусоривает  параметры функции
Я понимаю твою логику, но на мой взгляд писать по DDD - это не означает, что мы пишем так, что легко можем перемещать интерфейсы в другой проект на другом языке. Контекст - это фича именно го и это нормально его объявлять в интерфейсах, если нам нужно будет переписывать наш код на другой язык, то мы в любом случае будет многое менять и удаление контекста из сигнатуры интерфейсов не выглядит проблемой

2023-10-22 07:44 UTC, merged