Iter18
anoriar/shortener pull request #20
Opened 2023-12-23 17:17 UTC by anoriar

2023-12-25 09:18 UTC, gonozov0 requested changes
Отличная работа, круто, что выявил слабые места в проекте и проставил везде capacity при инициализации 👍
Оставил пару комментов

2023-12-25 09:18 UTC, gonozov0 commented on README.md
> +go tool pprof -http=":9090" profiles/base.pprof
Можно упростить до
go tool pprof -http=":9090" http://127.0.0.1:8081/debug/pprof/heap

2023-12-25 09:18 UTC, gonozov0 commented on cmd/shortener/main.go
> +				panic(err)
Это паника в горутине, она никак не повлияет на работу основного потока, поэтому лучше сделать log ошибки + os.exit

2023-12-25 09:18 UTC, gonozov0 commented on internal/e2e/client/dto/request/add_url_batch_request_dto.go
> +// AddURLBatchRequestDTO missing godoc.
Все доки такого типа просто для прохождения тестов? Считаешь, что не нужно их описывать?

2023-12-25 09:18 UTC, gonozov0 commented on internal/shortener/handlers/v2/addurlbatchhander/add_url_batch_handler.go
> +// correlation_id нужен для сопоставления урлов друг с другом. Поле не используется в БД
Такую документацию очень сложно читать, если лень самому, давай форматировать такой сплошной текст chatgpt

```go
// AddURLBatch добавляет несколько URL на основе входящего запроса.
//
// Процесс работы функции включает следующие шаги:
// 1. Генерация короткой версии для каждого URL.
// 2. Сохранение всех URL в базу данных.
// 3. Прикрепление сохранённых URL к конкретному пользователю.
// 4. Сопоставление входных и выходных данных по correlation_id и возврат сгенерированных коротких ссылок.
//
// Формат входных данных:
// [
//   {
//     "correlation_id": "by4564trg",
//     "original_url": "https://practicum3.yandex.ru"
//   },
//   ...
// ]
//
// Формат выходных данных:
// [
//   {
//     "correlation_id": "by4564trg",
//     "short_url": "http://localhost:8080/Ytq3tY"
//   },
//   ...
// ]
//
// Параметр correlation_id используется для сопоставления входных и выходных URL.
// Обратите внимание, что это поле не используется в базе данных.
```

2023-12-25 09:18 UTC, gonozov0 commented on internal/shortener/handlers/v2/getuserurlshandler/get_user_urls_handler.go
> +		w.WriteHeader(http.StatusUnauthorized)
Почему тут и ниже поменял статусы? Какие-то приколы в автотестах?

2023-12-25 09:18 UTC, gonozov0 commented on internal/shortener/middleware/compress/internal/reader/klauspost_gzip_compress_reader.go
> +	"github.com/klauspost/compress/gzip"
Не сталкивался с такой либой, в чем плюс по сравнению со стандартной?

2023-12-26 19:55 UTC, anoriar commented on internal/shortener/handlers/v2/getuserurlshandler/get_user_urls_handler.go
> +		w.WriteHeader(http.StatusUnauthorized)
да, теперь 401 если данных нет

2023-12-26 20:04 UTC, anoriar commented on internal/shortener/middleware/compress/internal/reader/klauspost_gzip_compress_reader.go
> +	"github.com/klauspost/compress/gzip"
Меньше ест памяти
Поставил для оптимизации запроса
Где то на 17% сократилось потребление компрессором памяти

2023-12-27 09:45 UTC, gonozov0 approved these changes
Работа принята 👍
Все моменты поправлены

2024-01-06 21:41 UTC, merged