Iter5
anoriar/shortener pull request #5
Opened 2023-09-09 19:12 UTC by anoriar

2023-09-11 16:40 UTC, gonozov0 requested changes
Отличная работа! Давай поправим читабельность и восприятие кода при использовании di контейнеров и улучшим покрытие тестов. В остальном супер, качественная реализация всех нужных структур.

2023-09-11 16:40 UTC, gonozov0 commented on cmd/client/main.go
> +}
Если есть желание, можно прокачать этот скрипт до полноценного e2e теста, нужно убрать пользовательский ввод и считывать все нужное из енв + вместо принтов использовать ассерты

2023-09-11 16:40 UTC, gonozov0 commented on cmd/shortener/main.go
> +	err = ctn.Clean()
По курсу еще не рассказывали про defer? Скорее всего пока нет, если знаешь, как работает, го заиспользуем, если нет, то пока оставляем так

2023-09-11 16:40 UTC, gonozov0 commented on internal/handlers/addurlhandler/add_url_handler_test.go
> +}
Хороший вопрос, на самом деле точно также, как ты и сделал, начинаем название с "mock", при использовании в реальном коде бизнес логики никто не будет использовать структуры, начинающиеся с этого.

У меня есть встречный вопрос по поводу целесообразности создания здесь мока. Тесты с использованием моков, которые возвращают что-то захаркоженное, имеют очень мало пользы. Важно мокать поведения внешних объектов, который идут куда-то во внешний мир, за пределы нашего приложения, например, в базу данных или какое-то стороннее api.
Если говорить про большие монолитные проекты, то там тоже уместно мокать походы в другие большие приложения (домены) нашего кода, но тут не тот случай.
Намного лучше будет убрать этот мок и передавать в хендлер как раз InMemoryStorage, что ты уже реализовал

2023-09-11 16:40 UTC, gonozov0 commented on internal/di/container.go
> +}
Этот код очень сложно воспринимать, очень круто, что ты уже освоил di подход через контейнеры, но на мой взгляд тут это яркий пример подхода [YAGNI](https://ru.wikipedia.org/wiki/YAGNI). Сейчас применение di с учетом того, что везде используем интерфейсы, явный оверхед, который еще и негативно сказывается на производительности из-за приведения типов.

Если не против, то давай уберем контейнеры из реалиазции.

Если очень хочешь использовать di контейнеры, то используй их только для storage и keygen. И для каждого используй свой собственный котейнер, так чтобы логика реализации этих структур была инкапсулирована и не доступна извне контейнера.
К примеру, в пакете storage у тебя будет лишь файл container.go c инициализацией контейнера и его публичными методами, а реальная логика будет находиться в storage/internal/storage/

2023-09-12 19:05 UTC, anoriar commented on cmd/shortener/main.go
> +	err = ctn.Clean()
Да, я понял, спасибо
Нужно было сразу после инциализации контейнера сделать defer ctn.Clean(). Сейчас уже не актуально, т к отказались от контейнера
Кстати вопрос про запуск сервера и defer
стоит ли обрабатывать паники в main.go через конструкцию defer recover?
И правильно ли вообще в main.go делать паники на любую ошибку?

2023-09-12 19:21 UTC, anoriar commented on internal/handlers/addurlhandler/add_url_handler_test.go
> +}
Поправил, но оставил ошибочный мок mockAddHandlerURLStorageError для проверки ошибочного поведения

Возможно в данном случае нецелесообразно использовать мок, т к хранилище глобальная переменная
Но уже в следующем спринте будет не InMemory, а база данных. И там все равно придется мокать.

Вопрос насчет тестов с бд: целесообразно ли делать тесты с использованием реальной бд (т е заполнять захардкоженными моделями базу) а потом проверять GetHandler? Или достаточно моков?

2023-09-12 19:27 UTC, anoriar commented on internal/di/container.go
> +}
Идея такого подхода подчерпнута из Symfony. Там есть контейнер зависимостей, который вообще может собираться из yaml файла. В Go такого удобного подхода нет. 
Хочется в go реализовать di, который будет затрачивать минимальные усилия по написанию кода для зависимостей
Либа saruslabi по факту эту проблему не решает. Все равно вообще все зависимости придется писать.

Не очень понял подход про container.go. Зачем в данном случае контейнеры для одного сервиса?
Можешь привести пример?
Сейчас разделил таким образом: для каждого хендлера или сервиса создал рядом файл init. Там метод Initialize
который собирает необходимый граф зависимостей. Это наиболее простой вариант и отвечает принципу единой ответственности.
Еще вопрос: смотрел что можно сделать иньекцию зависимостей через пакет wire. Там используется кодогенерация. На реальных проектах каким подходом лучше пользоваться?

2023-09-12 22:31 UTC, anoriar commented on cmd/client/main.go
> +}
Добавил тест
папка e2e
в internal и cmd соответственно

2023-09-13 07:24 UTC, gonozov0 commented on cmd/shortener/main.go
> +	err = ctn.Clean()
Отличный вопрос, если говорить в контексте веб сервера, то правильнее перехватывать паники через middleware, например, у [chi есть готовая реализация для этого](https://go-chi.io/#/pages/middleware?id=recoverer)

2023-09-13 07:26 UTC, gonozov0 commented on internal/handlers/addurlhandler/add_url_handler_test.go
> +}
Не совсем так, InMemory реализация у нас останется на равне с новой реализацией базы данных. Как раз смысл интерфейса в данном случае в том, что при запуске приложения мы будем использовать репозиторий базы данных, а для тестов оставим InMemory, чтобы в тестах не было походов во внешний мир.

2023-09-13 07:31 UTC, gonozov0 commented on internal/di/container.go
> +}
Я не пользовался кодогенерацией и в принципе сторонними решениями про инъекцию зависимостей, на мой взгляд лучше всего для этого использовать просто интерфейсный подход. Этот подход придерживается большинство в go сообществе и не сталкивался еще, где этого подхода было бы не достаточно для решения каких либо задач.
https://stackoverflow.com/questions/41900053/is-there-a-better-dependency-injection-pattern-in-golang

2023-09-13 07:36 UTC, gonozov0 approved these changes
Прекрасно, теперь код легко читать, воспринимать и расширять новой функциональностью!

2023-09-21 17:05 UTC, merged