Iter9
anoriar/shortener pull request #9
Opened 2023-10-01 13:13 UTC by anoriar

2023-10-02 08:47 UTC, gonozov0 requested changes
Отличная работа👍
Оставил пару комментов по улучшению кода
Особенно круто, что реализовал e2e тест и написал доку

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/router/router.go
> +func InitializeRouter(cnf *config.Config, logger *zap.Logger) *Router {
Не совсем понимаю, зачем разбил на 2 конструктора.

NewRouter, насколько вижу, нигде не используется, кроме как в этой функции, поэтому я бы логику текущего NewRouter перенес сюда, а этот конструктор переименовал в NewRouter, т.к. так принято называть конструкторы в go

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/handlers/v2/addurlhandler/add_url_handler.go
> +func Initialize(cnf *config.Config, urlRepository repository.URLRepositoryInterface) *AddHandler {
На мой взгляд, такие конструкторы только усложняют код, по крайней мере мне сложно было въехать зачем он и для чего. Давай лучше использовать напрямую в других местах кода New конструктуры без лишних прокси конструкторов

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/handlers/v2/addurlhandler/add_url_handler.go
> +	if _, err = govalidator.ValidateStruct(&addURLRequestDto); err != nil {
Я правильно понимаю, что этот код нужен для валидации урла внутри структуры? Если да, то я бы поискал лучше более явные просто функции, в которые необходимо передать само поле url

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/handlers/v2/addurlhandler/add_url_handler.go
> +		//#MENTOR: Возможно ли выходить из хендлера в одну строку? Без return. Например, возвращать ошибку? Часто натыкался на случаи, где забываю поставить return
возможно в каких-то фрейворках есть такое, но я не сталкивался, стараюсь всегда использовать стандартный http в хендлерах.

На мой взгляд, это наоборот хорошо, что мы явно указываем return
А если забыл вдруг написать, то на каждый такой BadRequest должен быть в реальных проектах отдельный тест, который отловит эту проблему

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/middleware/compress_middleware.go
> +	"github.com/anoriar/shortener/internal/shortener/shared/compress"
Не очень понимаю, почему решил поместить в shared, вроде только тут исопльзуется, поэтому стоит для compress_middleware сделать отдельный пакет, а внутрь него в internal поместить compress

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/services/url_gen/short_url_generator.go
> +var ErrShortKeyGenerationAttemptsExceeded = fmt.Errorf("max number of attempts for short url generation has been exhausted: %v", maxAttempts)
Зависит от ситуации, но в большинстве кейсов, на мой взгляд, лучше, как ты сделал, глобальные объекты ошибок

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/services/url_gen/short_url_generator.go
> +// Понимаю, что невозможно бесконечное количество комбинаций обычных урлов нельзя свести к ограниченному количеству комбинаций из 6 символов
Вообще для генерации id в большинстве проектов используется uuid4

В целом, я бы не стал тут проверять, что нет такого id в репозитории, как будто бы оверхед, можно просто увеличить количество символов в комбинации, если случались коллизии

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/file/reader/url_reader.go
> +package reader
reader и writer используются вроде только в fileUrlRepository, поэтому давай положим это в его пакет в internal

2023-10-02 08:47 UTC, gonozov0 commented on internal/shortener/file/reader/url_reader.go
> +	// Процедура декодирования json массива строк быстрее чем по одной строке?
Чанками есть смысл, если файл много весит, чтобы не вылезти за пределы по оперативной памяти. В целом для данной задачи читать чанками оверхед, но то, что реализовал - это оч круто

По производительности разницы сильной не будет, только если не читать чанками параллельно в разных горутинах, возможно есть уже либы, которые это делают, но вот это точно будет оверхедом)

Процедура декодирования json массива строк не быстрее чем по одной строке, т.к. декодирования массива строк все равно происходит синхронно

2023-10-03 10:07 UTC, anoriar commented on internal/shortener/services/url_gen/short_url_generator.go
> +// Понимаю, что невозможно бесконечное количество комбинаций обычных урлов нельзя свести к ограниченному количеству комбинаций из 6 символов
id и short_key - разные поля по ТЗ
id у меня это uuid4 (генерю через либу)
short_key - для пользователя

2023-10-03 11:22 UTC, anoriar commented on internal/shortener/router/router.go
> +func InitializeRouter(cnf *config.Config, logger *zap.Logger) *Router {
Так получится нарушение солид приципа Dependency Inversion
Нельзя просто так взять и создать новую зависимость внутри конструктора
Пример из книжек: наняли сотрудника. Ему обычно дают компьютер, мышку и клавиатуру, а не он сам покупает.
Если в конструкторе класса делать другие New, а не передавать их в аргументе - это и будет так, как будто он сам себе все покупает.

Здесь 2 контекста:
1 NewRouter - это конструктор, ему надо отдавать зависимости извне
2 Initialize - это фабрика объекта, которая инциализацирует вектор зависимостей по нему
Здесь кстати большой вопрос - нарушается ли принцип единой ответственности? Ведь функция Initialize не принадлежит типу, хотя и в одном файле =)

До этого варианта реализации делал отдельный файл init.go с одной функцией initialize
Какое решение лучше? Может есть еще варианты?

2023-10-03 11:22 UTC, anoriar commented on internal/shortener/handlers/v2/addurlhandler/add_url_handler.go
> +func Initialize(cnf *config.Config, urlRepository repository.URLRepositoryInterface) *AddHandler {
См пункт выше про router

2023-10-04 07:58 UTC, gonozov0 commented on internal/shortener/router/router.go
> +func InitializeRouter(cnf *config.Config, logger *zap.Logger) *Router {
Согласен с тобой про Dependency Inversion и отличный пример ты привел, но твоем случае Initialize функции все равно больше похожи на конструктор, а не фабрики, т.к. объявлены в том же файле и, к примеру, тот же пакет addurlhandler все равно имеет зависимость на urlgen, как ни крути. А текущие конструкторы ничем не отличаются от того, чтобы инициализировать структуру без них, т.к. нет никакой дополнительной логики при создании.

Стоит поместить фабрики в отдельный пакет и сами реализации с кострукторами в internal внутрь фабрик.
Либо сделать текущие конструктуры (New...) неэкспортируемыми, т.к. за пределами пакета используются только Initialize... функции.

Не настаиваю на этих изменениях, можешь оставить, как есть, это холеварная тема и то, что у тебя есть свое мнение на этот счет это круто)

2023-10-04 08:04 UTC, gonozov0 approved these changes
Работа сдана 👍
Критичных моментов не осталось

2023-10-05 17:34 UTC, merged